"""added join table

Revision ID: 322332523900
Revises: c52129910c4d
Create Date: 2023-09-22 18:41:25.456552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322332523900'
down_revision = 'c52129910c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], name=op.f('fk_album_collections_album_id_album')),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_album_collections_collection_id_collection')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_collections')
    # ### end Alembic commands ###
